universe              = vanilla
arguments             = $(par1) $(par2)
executable            = DiMuonTkAlZMuMuValidator.sh
output                = $(par2)/outfiles/ZtoMuMuNtuplization_condor_$(par1).out
error                 = $(par2)/outfiles/ZtoMuMuNtuplization_condor_$(par1).err
log                   = $(par2)/outfiles/ZtoMuMuNtuplization_condor_$(par1).log
transfer_output_files = ""
+JobFlavour = "tomorrow" 
queue