import FWCore.ParameterSet.Config as cms

from RecoMuon.TransientTrackingRecHit.MuonTransientTrackingRecHitBuilderESProducer import MuonTransientTrackingRecHitBuilderESProducer as _MuonTransientTrackingRecHitBuilderESProducer

hltESPMuonTransientTrackingRecHitBuilder = _MuonTransientTrackingRecHitBuilderESProducer(
    ComponentName = cms.string('hltESPMuonTransientTrackingRecHitBuilder')
)
