import FWCore.ParameterSet.Config as cms

from RecoLocalMuon.CSCRecHitD.CSCRecHitDProducer import CSCRecHitDProducer as _CSCRecHitDProducer

hltCsc2DRecHits = _CSCRecHitDProducer(
    CSCDebug = cms.untracked.bool(False),
    CSCNoOfTimeBinsForDynamicPedestal = 2,
    CSCStripClusterChargeCut = 25.0,
    CSCStripPeakThreshold = 10.0,
    CSCStripxtalksOffset = 0.03,
    CSCUseCalibrations = True,
    CSCUseGasGainCorrections = False,
    CSCUseReducedWireTimeWindow = False,
    CSCUseStaticPedestals = False,
    CSCUseTimingCorrections = True,
    CSCWireClusterDeltaT = 1,
    CSCWireTimeWindowHigh = 15,
    CSCWireTimeWindowLow = 0,
    CSCstripWireDeltaTime = 8,
    ConstSyst_ME12 = 0.02,
    ConstSyst_ME13 = 0.03,
    ConstSyst_ME1a = 0.01,
    ConstSyst_ME1b = 0.02,
    ConstSyst_ME21 = 0.03,
    ConstSyst_ME22 = 0.03,
    ConstSyst_ME31 = 0.03,
    ConstSyst_ME32 = 0.03,
    ConstSyst_ME41 = 0.03,
    NoiseLevel_ME12 = 7.0,
    NoiseLevel_ME13 = 4.0,
    NoiseLevel_ME1a = 9.0,
    NoiseLevel_ME1b = 6.0,
    NoiseLevel_ME21 = 5.0,
    NoiseLevel_ME22 = 7.0,
    NoiseLevel_ME31 = 5.0,
    NoiseLevel_ME32 = 7.0,
    NoiseLevel_ME41 = 5.0,
    UseAverageTime = False,
    UseFivePoleFit = True,
    UseParabolaFit = False,
    XTasymmetry_ME12 = 0.015,
    XTasymmetry_ME13 = 0.02,
    XTasymmetry_ME1a = 0.023,
    XTasymmetry_ME1b = 0.01,
    XTasymmetry_ME21 = 0.023,
    XTasymmetry_ME22 = 0.023,
    XTasymmetry_ME31 = 0.023,
    XTasymmetry_ME32 = 0.023,
    XTasymmetry_ME41 = 0.023,
    readBadChambers = True,
    readBadChannels = False,
    stripDigiTag = ("simMuonCSCDigis","MuonCSCStripDigi"),
    wireDigiTag = ("simMuonCSCDigis","MuonCSCWireDigi")
)
