import FWCore.ParameterSet.Config as cms

from RecoEcal.EgammaClusterProducers.PFECALSuperClusterProducer import PFECALSuperClusterProducer as _PFECALSuperClusterProducer

hltParticleFlowSuperClusterHGCal = _PFECALSuperClusterProducer(
    BeamSpot = ("hltOnlineBeamSpot"),
    ClusteringType = cms.string('Mustache'),
    ESAssociation = ("hltParticleFlowClusterECAL"),
    EnergyWeight = cms.string('Raw'),
    PFBasicClusterCollectionBarrel = cms.string('particleFlowBasicClusterECALBarrel'),
    PFBasicClusterCollectionEndcap = cms.string(''),
    PFBasicClusterCollectionPreshower = cms.string('particleFlowBasicClusterECALPreshower'),
    PFClusters = ("hltParticleFlowClusterHGCal"),
    PFSuperClusterCollectionBarrel = cms.string('particleFlowSuperClusterECALBarrel'),
    PFSuperClusterCollectionEndcap = cms.string(''),
    PFSuperClusterCollectionEndcapWithPreshower = cms.string(''),
    applyCrackCorrections = False,
    barrelRecHits = ("hltEcalRecHit","EcalRecHitsEB"),
    doSatelliteClusterMerge = False,
    dropUnseedable = True,
    endcapRecHits = ("hltEcalRecHit","EcalRecHitsEE"),
    etawidth_SuperClusterBarrel = 0.04,
    etawidth_SuperClusterEndcap = 0.04,
    isOOTCollection = False,
    mightGet = cms.optional.untracked.vstring,
    phiwidth_SuperClusterBarrel = 0.6,
    phiwidth_SuperClusterEndcap = 0.6,
    regressionConfig = dict(
        applySigmaIetaIphiBug = False,
        eRecHitThreshold = 1,
        ecalRecHitsEB = ("hltEcalRecHit","EcalRecHitsEB"),
        ecalRecHitsEE = ("hltEcalRecHit","EcalRecHitsEE"),
        hgcalCylinderR = 2.79999995232,
        hgcalRecHits = (""),
        isHLT = False,
        isPhaseII = False,
        regressionKeyEB = cms.string('pfscecal_EBCorrection_offline_v2'),
        regressionKeyEE = cms.string('pfscecal_EECorrection_offline_v2'),
        regressionMaxEB = 2,
        regressionMaxEE = 2,
        regressionMinEB = 0.2,
        regressionMinEE = 0.2,
        uncertaintyKeyEB = cms.string('pfscecal_EBUncertainty_offline_v2'),
        uncertaintyKeyEE = cms.string('pfscecal_EEUncertainty_offline_v2'),
        uncertaintyMaxEB = 0.5,
        uncertaintyMaxEE = 0.5,
        uncertaintyMinEB = 0.0002,
        uncertaintyMinEE = 0.0002,
        vertexCollection = ("hltOfflinePrimaryVertices")
    ),
    satelliteClusterSeedThreshold = 50,
    satelliteMajorityFraction = 0.5,
    seedThresholdIsET = True,
    thresh_PFClusterBarrel = 0,
    thresh_PFClusterES = 0,
    thresh_PFClusterEndcap = 0.15,
    thresh_PFClusterSeedBarrel = 1,
    thresh_PFClusterSeedEndcap = 1,
    thresh_SCEt = 4,
    useDynamicDPhiWindow = True,
    useRegression = False,
    verbose = cms.untracked.bool(False)
)
