import FWCore.ParameterSet.Config as cms

from RecoEcal.EgammaClusterProducers.PFECALSuperClusterProducer import PFECALSuperClusterProducer as _PFECALSuperClusterProducer

hltParticleFlowSuperClusterHGCalFromTICLL1Seeded = _PFECALSuperClusterProducer(
    BeamSpot = ("hltOnlineBeamSpot"),
    ClusteringType = cms.string('Mustache'),
    ESAssociation = ("hltParticleFlowClusterECALL1Seeded"),
    EnergyWeight = cms.string('Raw'),
    PFBasicClusterCollectionBarrel = cms.string('particleFlowBasicClusterECALBarrel'),
    PFBasicClusterCollectionEndcap = cms.string(''),
    PFBasicClusterCollectionPreshower = cms.string('particleFlowBasicClusterECALPreshower'),
    PFClusters = ("hltParticleFlowClusterHGCalFromTICLL1Seeded"),
    PFSuperClusterCollectionBarrel = cms.string('particleFlowSuperClusterECALBarrel'),
    PFSuperClusterCollectionEndcap = cms.string(''),
    PFSuperClusterCollectionEndcapWithPreshower = cms.string(''),
    applyCrackCorrections = False,
    barrelRecHits = ("hltRechitInRegionsECAL","EcalRecHitsEB"),
    doSatelliteClusterMerge = False,
    dropUnseedable = True,
    endcapRecHits = ("hltRechitInRegionsECAL","EcalRecHitsEE"),
    etawidth_SuperClusterBarrel = 0.04,
    etawidth_SuperClusterEndcap = 0.04,
    isOOTCollection = False,
    mightGet = cms.optional.untracked.vstring,
    phiwidth_SuperClusterBarrel = 0.6,
    phiwidth_SuperClusterEndcap = 0.6,
    regressionConfig = dict(
        applySigmaIetaIphiBug = False,
        eRecHitThreshold = 1,
        ecalRecHitsEB = ("hltEcalRecHitL1Seeded","EcalRecHitsEB"),
        ecalRecHitsEE = ("hltEcalRecHitL1Seeded","EcalRecHitsEE"),
        hgcalRecHits = ("hltParticleFlowRecHitHGCL1Seeded"),
        isHLT = True,
        isPhaseII = True,
        regressionKeyEB = cms.string('pfscecal_EBCorrection_offline_v2'),
        regressionKeyEE = cms.string('superclus_hgcal_mean_online'),
        uncertaintyKeyEB = cms.string('pfscecal_EBUncertainty_offline_v2'),
        uncertaintyKeyEE = cms.string('superclus_hgcal_sigma_online'),
        vertexCollection = ("")
    ),
    satelliteClusterSeedThreshold = 50,
    satelliteMajorityFraction = 0.5,
    seedThresholdIsET = True,
    thresh_PFClusterBarrel = 0,
    thresh_PFClusterES = 0,
    thresh_PFClusterEndcap = 0.15,
    thresh_PFClusterSeedBarrel = 1,
    thresh_PFClusterSeedEndcap = 1,
    thresh_SCEt = 10.0,
    useDynamicDPhiWindow = True,
    useRegression = True,
    verbose = cms.untracked.bool(False)
)
