import FWCore.ParameterSet.Config as cms

from RecoHGCal.TICL.TrackstersMergeProducer import TrackstersMergeProducer as _TrackstersMergeProducer

hltTiclTrackstersMerge = _TrackstersMergeProducer(
    cosangle_align = 0.9945,
    detector = cms.string('HGCAL'),
    e_over_h_threshold = 1,
    eid_input_name = cms.string('input'),
    eid_min_cluster_energy = 2.5,
    eid_n_clusters = 10,
    eid_n_layers = 50,
    eid_output_name_energy = cms.string('output/regressed_energy'),
    eid_output_name_id = cms.string('output/id_probabilities'),
    eta_bin_window = 1,
    halo_max_distance2 = 4,
    layer_clusters = ("hltHgcalMergeLayerClusters"),
    layer_clustersTime = ("hltHgcalMergeLayerClusters","timeLayerCluster"),
    linkingPSet = dict(
        algo_verbosity = 0,
        cutTk = cms.string('1.48 < abs(eta) < 3.0 && pt > 1. && quality("highPurity") && hitPattern().numberOfLostHits("MISSING_OUTER_HITS") < 5'),
        delta_tk_ts_interface = 0.03,
        delta_tk_ts_layer1 = 0.02,
        delta_ts_em_had = 0.03,
        delta_ts_had_had = 0.03,
        track_time_quality_threshold = 0.5,
        type = cms.string('LinkingAlgoByDirectionGeometric')
    ),
    mightGet = cms.optional.untracked.vstring,
    muons = ("hltPhase2L3Muons"),
    optimiseAcrossTracksters = True,
    phi_bin_window = 1,
    propagator = cms.string('PropagatorWithMaterial'),
    pt_neutral_threshold = 2,
    pt_sigma_high = 2,
    pt_sigma_low = 2,
    resol_calo_offset_em = 1.5,
    resol_calo_offset_had = 1.5,
    resol_calo_scale_em = 0.15,
    resol_calo_scale_had = 0.15,
    tfDnnLabel = cms.string('tracksterSelectionTf'),
    track_max_eta = 3,
    track_max_missing_outerhits = 5,
    track_min_eta = 1.48,
    track_min_pt = 1,
    tracks = ("hltGeneralTracks"),
    tracksTime = ("tofPID","t0"),
    tracksTimeErr = ("tofPID","sigmat0"),
    tracksTimeQual = ("mtdTrackQualityMVA","mtdQualMVA"),
    trackstersclue3d = ("hltTiclTrackstersCLUE3DHigh"),
    useMTDTiming = False
)
